spring:
    application:
        name: Server
    datasource:
      hikari:
#          driver-class-name: org.postgresql.Driver
#          jdbc-url: jdbc:postgresql://localhost:5432/test
#          username: postgres
#          password: root
#          pool-name: postgresqlPool
          driver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:mem:testDB
          username: sa
          password:
          pool-name: H2Pool
          minimum-idle: 1
          maximum-pool-size: 5
          connection-timeout: 10000
          validation-timeout: 5000
          idle-timeout: 600000
    docker:
        compose:
            enabled: false
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            encoding: UTF-8

mybatis:
    mapper-locations: classpath:mappers/*.xml
    config-location: classpath:mybatis-config.xml
logging:
    config: classpath:logback-local.xml

