package com.peer.message;
public enum MessageType{
    TALK,
    DISCONNECT,
    CONNECT,
    CONNECTRESPONSE,
    CREATEREQUEST,
    RESULTRESPONSE,
    CURRENTCHATTINGROOMREQUEST,
    CURRENTCHATTINGROOMRESPONSE
}
